#!/usr/bin/env python
# Compass_test_v1a
import RPi.GPIO as GPIO
import time
import smbus
import math
GPIO.setmode(GPIO.BOARD) # Numbers GPIOs by physical location
# ========================================================================
#  COMPASS SENSOR CODE==================================================

bus = smbus.SMBus(1)  # changed from 0 to 1 in ()
address = 0x1e
def read_byte(adr):
	return bus.read_byte_data(address, adr)
def read_word(adr):
	high = bus.read_byte_data(address, adr)
	low = bus.read_byte_data(address, adr+1)
	val = (high << 8) + low
	return val

def read_word_2c(adr):
	val = read_word(adr)
	if (val >= 0x8000):
		return -((65535 - val) + 1)
	else:
		return val

def write_byte(adr, value):
	bus.write_byte_data(address, adr, value)

write_byte(0, 0b01110000) # Set to 8 samples @ 15Hz
write_byte(1, 0b00100000) # 1.3 gain LSb / Gauss 1090 (default)
write_byte(2, 0b00000000) # Continuous sampling

scale = 0.92

x_offset = -20
y_offset = -142

def get_bearing():
	x_out = (read_word_2c(3) - x_offset) * scale
	y_out = (read_word_2c(7) - y_offset) * scale
	z_out = (read_word_2c(5)) * scale


	bearing  = math.atan2(y_out, x_out)

	if (bearing < 0):
		bearing += 2 * math.pi
	return round(math.degrees(bearing),2)
# END COMPASS SENSOR CODE ==========================


try: 
	while True:
    		current_bearing=get_bearing()
    		print "bearing=",current_bearing
    		time.sleep(1)

except KeyboardInterrupt:
 	 # User pressed CTRL-C
  	#	 Reset GPIO settings
  	GPIO.cleanup()
