#!/usr/bin/env python
#  module_measure_distance_v1a.py  contains measure distance function

#================================================
# define measure_distance functions
#---------------------------------------------------------------------------------------------------
import RPi.GPIO as GPIO
import time

def measure_distance(TRIG,ECHO):
	GPIO.output(TRIG, False)
	pulse_start=0  # initialize variables 
	pulse_end=0

	GPIO.output(TRIG, True)
	time.sleep(0.00001)
	GPIO.output(TRIG, False)

	while GPIO.input(ECHO)==0:
		pulse_start = time.time()

	while GPIO.input(ECHO)==1:
  		pulse_end = time.time()

	pulse_duration = pulse_end - pulse_start

	distance = pulse_duration * 17150
	distance = round(distance, 2)
	return distance
#=====================================================================================================
